/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CorrGoods: typeof import('./src/components/CorrGoods/CorrGoods.vue')['default']
    CorrStore: typeof import('./src/components/CorrStore/CorrStore.vue')['default']
    DataColumn: typeof import('./src/components/DataColumn/DataColumn.vue')['default']
    DataExtraction: typeof import('./src/components/DataExtraction/DataExtraction.vue')['default']
    DataPreview: typeof import('./src/components/DataPreview/DataPreview.vue')['default']
    DataSource: typeof import('./src/components/DataSource/DataSource.vue')['default']
    DialogDbConfig: typeof import('./src/components/DialogDbConfig/DialogDbConfig.vue')['default']
    ElAutoResizer: typeof import('element-plus/es')['ElAutoResizer']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTableV2: typeof import('element-plus/es')['ElTableV2']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTree: typeof import('element-plus/es')['ElTree']
    LayoutBarMenu: typeof import('./src/components/LayoutBarMenu/LayoutBarMenu.vue')['default']
    LayoutHeader: typeof import('./src/components/LayoutHeader/LayoutHeader.vue')['default']
    LayoutMain: typeof import('./src/components/LayoutMain/LayoutMain.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableReporting: typeof import('./src/components/TableReporting/TableReporting.vue')['default']
    TableV2: typeof import('./src/components/TableV2/TableV2.vue')['default']
    VersionUpdate: typeof import('./src/components/versionUpdate/versionUpdate.vue')['default']
  }
}
